version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      # install npm dependencies/packages
      - echo Installing npm packages
      - npm install
  build:
    commands:
      # build
      - echo Building
      - npm run build

artifacts:
  files:
    # represents all files recursively
    - "**/*"
  # directory of files and subdirectories to include in build output artifacts
  base-directory: build
